name: lotm_grafting_ability
version: '1.0'
main: de.einlumian.lotm_grafting_ability.Lotm_grafting_ability
api-version: '1.20'

commands:
  grafting:
    description: Main grafting command
    usage: /grafting give <type>
    permission: grafting.give

permissions:
  grafting.give:
    description: Allows the player to get the Grafting item
    default: op